<a href="https://colab.research.google.com/github/pr31988/PyTorch-Fundamentals/blob/main/PyTorch_Fundamentals_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
vector = torch.tensor([1, 2, 3, 4])
matrix = torch.tensor([[1, 2], [3, 4]])
tensor_3d = torch.tensor([[[1, 2, 9, 10], [3, 4, 11, 12], [21, 22, 23, 24]], [[5, 6, 13, 14], [7, 8, 15, 16], [31, 32, 33, 34]], [[33, 44, 55, 66], [77, 88, 99, 22], [110, 230, 345, 445]]])
print(vector)
print(matrix)
print(tensor_3d)
print(vector.shape)
print(matrix.shape)
print(tensor_3d.shape)
print(vector.ndim)
print(matrix.ndim)
print(tensor_3d.ndim)


tensor([1, 2, 3, 4])
tensor([[1, 2],
        [3, 4]])
tensor([[[  1,   2,   9,  10],
         [  3,   4,  11,  12],
         [ 21,  22,  23,  24]],

        [[  5,   6,  13,  14],
         [  7,   8,  15,  16],
         [ 31,  32,  33,  34]],

        [[ 33,  44,  55,  66],
         [ 77,  88,  99,  22],
         [110, 230, 345, 445]]])
torch.Size([4])
torch.Size([2, 2])
torch.Size([3, 3, 4])
1
2
3


In [ ]:
tensor_2d = torch.tensor([[1, 11, 111, 1111], [2, 22, 222, 2222], [3, 33, 333, 3333]])
print(tensor_2d)
print(tensor_2d.shape)
print(tensor_2d.ndim)

tensor([[   1,   11,  111, 1111],
        [   2,   22,  222, 2222],
        [   3,   33,  333, 3333]])
torch.Size([3, 4])
2


In [ ]:
random_tensor = torch.rand(1, 3, 4)
print(random_tensor)
print(random_tensor.shape)
print(random_tensor.ndim)

tensor([[[0.6658, 0.8918, 0.0371, 0.1324],
         [0.0456, 0.1901, 0.4299, 0.8673],
         [0.5915, 0.6786, 0.8269, 0.1786]]])
torch.Size([1, 3, 4])
3


In [ ]:
tensor_arange = torch.arange(start=10, end=100, step=10)
print(tensor_arange)

tensor_zeros = torch.zeros(size=(3, 5))
print(tensor_zeros)

tensor_ones = torch.ones(size=(3, 4))
print(tensor_ones)

torch_mult = torch.ones(size=(3, 4)) * 2
print(torch_mult)

torch_add = tensor_ones + torch_mult
print(torch_add)

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [ ]:
%%time
tensor_16bit = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float16)
print(tensor_16bit)
tensor_32bit = tensor_16bit.type(torch.float32)
print(tensor_32bit)
print(tensor_16bit * tensor_32bit)
print(f"device of tesnsor: {tensor_16bit.device}")
mult_tensor = torch.tensor([[1, 2, 3]])
mult_tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(torch.matmul(mult_tensor, mult_tensor2))

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
device of tesnsor: cpu
tensor([[30, 36, 42]])
CPU times: user 11.4 ms, sys: 1.14 ms, total: 12.6 ms
Wall time: 57.8 ms


In [ ]:
tensor_B = tensor_16bit.T
print(tensor_B)
print(tensor_B.shape)
print(torch.mm(tensor_16bit, tensor_B))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]], dtype=torch.float16)
torch.Size([3, 2])
tensor([[14., 32.],
        [32., 77.]], dtype=torch.float16)


In [ ]:
# min, max, argmin(positional value), argmax (positional value), sum
x = torch.arange(2,100,10)
print(x)
print(x.min())
print(x.max())
print(x.type(torch.float32).mean())
print(x.type(torch.float32).max())
print(torch.sum(x), x.sum())
torch.argmax(x), torch.argmin(x)

tensor([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])
tensor(2)
tensor(92)
tensor(47.)
tensor(92.)
tensor(470) tensor(470)


(tensor(9), tensor(0))

# reshaping, squeezing, unsqueezing, stacking tensor --- tensor manipulation
* reshaping : reshape input tensor to defined shape
* view : return a view of input tensor after reshaping. view shares same memory of original input
* squeezing : removing '1' dimention
* unsqueezing : adding '1' dimention

In [ ]:
tensor_m = torch.arange(0,120,10)
print(tensor_m, tensor_m.shape)
print(tensor_m.reshape(3,4))
tensor_m.reshape(2,6)

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110]) torch.Size([12])
tensor([[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110]])


tensor([[  0,  10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100, 110]])

In [ ]:
import torch
tensor_z = torch.arange(1,10)
print('tensor_z before view:', tensor_z, tensor_z.shape)
tensor_x = tensor_z.view(3,3)
print('tensor_z after view:',tensor_z, tensor_z.shape)
tensor_x, tensor_x.shape

tensor_z before view: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor_z after view: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])


(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
tensor_x[:, 0] = 15
tensor_z, tensor_x

(tensor([15,  2,  3, 15,  5,  6, 15,  8,  9]),
 tensor([[15,  2,  3],
         [15,  5,  6],
         [15,  8,  9]]))

In [ ]:
torch.stack([tensor_x, tensor_x, tensor_x],dim=0)

tensor([[[15,  2,  3],
         [15,  5,  6],
         [15,  8,  9]],

        [[15,  2,  3],
         [15,  5,  6],
         [15,  8,  9]],

        [[15,  2,  3],
         [15,  5,  6],
         [15,  8,  9]]])

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x)
y = torch.squeeze(x)
print(y)
y.size()
z = torch.unsqueeze(y, 1)
print(f"unsqueesed tensor: {z}")
z.size()

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
unsqueesed tensor: tensor([[[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]]])


torch.Size([2, 1, 2, 2])

In [ ]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)  #shares same memory as x_original
print(f"Original shape: {x_original.shape}")
print(f"Permuted shape: {x_permuted.shape}")

Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


In [ ]:
x_original [0,0,0] = 1234
x_original[0,0,0], x_permuted[0,0,0]

(tensor(1234.), tensor(1234.))

In [ ]:
x = torch.arange(1, 13).reshape(2, 3,2)
x, x.shape

(tensor([[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],
 
         [[ 7,  8],
          [ 9, 10],
          [11, 12]]]),
 torch.Size([2, 3, 2]))

In [ ]:
x[1][0][1], x[:][0]

(tensor(8),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [ ]:
x[0][:,0], x[1, 1, 0], x [1, :,1]

(tensor([1, 3, 5]), tensor(9), tensor([ 8, 10, 12]))

In [ ]:
# numPy array to tensor. default datatype for numPy: float64, default datatype for pyTorch: float32
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch
torch.manual_seed(0)
torch_tensor_A = torch.rand(3, 4)
torch.manual_seed(0)
torch_tensor_B = torch.rand(3, 4)
print(torch_tensor_A)
print(torch_tensor_B)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])


In [ ]:
!nvidia-smi

Thu Nov 21 12:08:27 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# set the device to use cuda --> device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'device:' , device)
torch.cuda.device_count()

device: cuda


1

In [ ]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)
tensor_on_gpu = tensor.to(device) # move tensor to gpu
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy() # to make tensor work with numPy() move it back to cpu
tensor_back_on_cpu, tensor_back_on_cpu.dtype

(array([1, 2, 3]), dtype('int64'))

## Exercise

In [ ]:
tensor_r = torch.rand(7, 7)
print(tensor_r)

tensor([[0.1127, 0.2858, 0.5574, 0.1532, 0.0089, 0.9727, 0.0901],
        [0.5818, 0.1922, 0.9449, 0.1056, 0.0454, 0.1010, 0.8972],
        [0.1263, 0.2523, 0.5602, 0.4536, 0.7598, 0.4564, 0.9742],
        [0.3615, 0.6249, 0.0838, 0.5999, 0.3883, 0.6762, 0.2671],
        [0.8114, 0.4410, 0.4355, 0.7109, 0.6530, 0.7796, 0.8178],
        [0.6309, 0.3842, 0.1739, 0.1758, 0.1401, 0.3908, 0.9653],
        [0.9041, 0.7723, 0.7890, 0.9554, 0.4080, 0.4032, 0.5521]])


In [ ]:
import torch
tensor_t = torch.rand(1, 7)
print(tensor_t)

tensor([[0.1797, 0.1855, 0.2051, 0.8906, 0.4805, 0.7098, 0.1323]])


In [ ]:
tensor_p = torch.matmul(tensor_r, tensor_t.T)
print(tensor_p)

tensor([[1.0307],
        [0.6403],
        [1.4063],
        [1.4342],
        [1.9253],
        [0.8492],
        [1.8738]])


In [ ]:
torch.manual_seed(0)
torch_r = torch.rand([7,7])
torch.manual_seed(0)
torch_t = torch.rand([7,1])
print(torch_r, torch_t)
torch_p = torch.matmul(torch_r, torch_t)
torch_p

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]) tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [1]:
import torch
torch.manual_seed(1234)
tensor_gpu_A = torch.rand([1,4])
print(tensor_gpu_A, tensor_gpu_A.device)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor_gpu_p = tensor_gpu_A.to(device)
tensor_gpu_p

tensor([[0.0290, 0.4019, 0.2598, 0.3666]]) cpu


tensor([[0.0290, 0.4019, 0.2598, 0.3666]], device='cuda:0')

In [2]:
torch.manual_seed(1234)
tensor_sendTo_gpu_A = torch.rand([2,3])

torch.manual_seed(1234)
tensor_sendTo_gpu_B = torch.rand([2,3])
print(tensor_sendTo_gpu_A, tensor_sendTo_gpu_B)

tensor_send_gpu_A = tensor_sendTo_gpu_A.to(device)
tensor_send_gpu_B = tensor_sendTo_gpu_B.to(device)
tensor_send_gpu_A, tensor_send_gpu_B

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [5]:
tensor_c = torch.matmul(tensor_send_gpu_A, tensor_send_gpu_B.T)
tensor_c

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [8]:
print (tensor_c.min(), tensor_c.max())
torch.argmin(tensor_c), torch.argmax(tensor_c)

tensor(0.2161, device='cuda:0') tensor(0.6287, device='cuda:0')


(tensor(1, device='cuda:0'), tensor(3, device='cuda:0'))

In [16]:
torch.manual_seed(7)
tensor_ab = torch.rand([1,1,1,10])
tensor_cd = torch.squeeze(tensor_ab)
tensor_ab, tensor_ab.shape, tensor_cd, tensor_cd.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))